version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=db
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=news_api_dev
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database_mysql:/var/lib/mysql2
  app:
    build: .
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
volumes:
  database_mysql:
networks:
  my-network:
    driver: bridge