version: '3'
services:
  db:
    image: arm64v8/mysql:oracle
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_api_dev
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
volumes:
  mysql:
networks:
  my-network:
    driver: bridge